### ISSUE TITLE
Bug: When using this mod, even advanced tooltips go invisible.

### ISSUE THREAD

**Issue by remclave** [thraaawn/ColoredTooltips#1]
This issue has affected every version of mod pack I've used your mod. When this mod is installed, I lose the ability to see any of the tooltips. Most notable is when Thaumcraft is installed. All of the aspects that would normally be visible completely disappear.

So your mod is either disabling all normal and advanced tooltips or the "background" is actually eclipsing them thus making them appear disabled.

(on a different note: I really like most of your mods. this one just fell short...)

**Comment by davenonymous** [comment]
I'd recommend switching to Darkhax' [Coloured Tooltips](https://minecraft.curseforge.com/projects/coloured-tooltips).
It does things much cleaner than the hack this mod is using.

**Comment by remclave** [comment]
Thank you for your reply. I will let my modpack owner know about this if it is still his desire to include the option for any 'colored' tooltips.
